version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12
        commands:
            - echo "we are here"
            - apt install npm
    build:
        commands:
            - npm run build
