version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 14
        commands:
            - echo "we are here"
            - apt-get update
            - node -v
            - apt-get install npm -y
            - npm i
            - ls
    build:
        commands:
            - npm run build
            - ls
            - cd ./build && ls
    post_build:
        commands:
            - mv appspec.yml /build
artifacts:
    files:
        - "**/*"
    base-directory: 'build'
    discard-paths: no
