version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 14
        commands:
            - echo "we are here"
            - apt-get update
            - node -v
            - apt-get install npm -y
            - npm i
            - ls
    build:
        commands:
            - npm run build
            - ls
    post_build:
        commands:
            - ls
            - cp ./appspec.yml /build
            - cd ./build && ls
artifacts:
    files:
        - "**/*"
    base-directory: 'build'
    discard-paths: no
    secondary-artifacts:
        artifact1:
      files:
        - appspec.yml
      name: secondary-artifact-name-1
