version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 14
        commands:
            - echo "we are here"
            - apt-get update
            - node -v
            - apt-get install npm -y
            - npm i
            - mkdir hello
            - ls
    build:
        commands:
            - npm run build
            - ls
            - mv build/* hello
            - cd ./hello && ls
            - cd ..
    post_build:
        commands:
            - ls
            - mv appspec.yml /build
            - cd ./build && ls
artifacts:
    files:
        - "**/*"
        - "*/appspec.yml"
    base-directory: 'build'
    discard-paths: no


   
