version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 14
        commands:
            - echo "we are here"
            - apt-get install npm
    build:
        commands:
            - npm run build
