version: 0.0

phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo "we are here"
            - sudo apt install npm
    build:
        commands:
            - npm run build
